image: docksal/ci-agent:php

pipelines:
  default:
    - step:
        script:
          - source build-env  # Initialize the agent configuration
          - build-init  # Initialize the remote sandbox environment
          - slack "Started sandbox build for branch *${BITBUCKET_BRANCH}*"  # post to Slack
          - build-exec "fin init"  # Run fin init on the remote docker host to provision a sandbox
          - build-exec "cd docroot && fin drush st"  # Run other commands on the sandbox server
          - slack "Completed sandbox build for branch *${BITBUCKET_BRANCH}*:\n<http://${SANDBOX_DOMAIN}|http://${SANDBOX_DOMAIN}>"
